# Generated by Django 5.1.5 on 2025-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orderitem_price_alter_orderitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
