# Generated by Django 4.2.7 on 2024-12-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_orderitem_alter_filterprice_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact_us',
        ),
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='Images',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
