# Generated by Django 5.1.5 on 2025-02-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
