# Generated by Django 4.2.7 on 2025-01-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
