# Generated by Django 4.2.7 on 2025-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_order_paid_remove_order_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the About Page', max_length=200)),
                ('content', models.TextField(help_text='Content of the About Page')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
