# Generated by Django 4.2.7 on 2025-01-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='rating',
        ),
    ]
