# Generated by Django 5.1.5 on 2025-01-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_images_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
    ]
